### ISSUE TITLE
No icons after "Show menu bar" and go back

### ISSUE THREAD

**Issue by smarquespt** [Lootyhoof/photonic#1]
How to reproduce:

1 - Set menu bar as hidden
![1](https://user-images.githubusercontent.com/1302668/52513517-2ba0e700-2c03-11e9-9cb7-4abfedd41177.png)

2 - Enable "Show menu bar"
![2](https://user-images.githubusercontent.com/1302668/52513520-2fcd0480-2c03-11e9-9588-2e0d22798c43.png)

3 - Disable "show menu bar"
![3](https://user-images.githubusercontent.com/1302668/52513523-32c7f500-2c03-11e9-9231-35402687ea10.png)

In last screenshot seems to be shown but they are not. But if you click somewhere the icons are back.

**Comment by Lootyhoof** [comment]
Yes, this is due to how the toolbars are processed by the browser. It's not something I can change without changing how the theme is designed (since it tries to look like Firefox, which styles its windows with the same colours). This only happens when accent colours (in Windows) are not applied to the titlebar.

If you really need to enable/disable the menubar like this, you could set tabs on top which negates the issue. Or apply an accent colour to the titlebar in Windows.

**Comment by Lootyhoof** [comment]
Although...I might be able to work around this somewhat. I'll think about this.

**Comment by smarquespt** [comment]
It's fixed indeed. Thanks
