### ISSUE TITLE
[feature request] compact mode

### ISSUE THREAD

**Issue by hosxy** [Lootyhoof/photonic#3]
Could you please add a "compact mode"  like firefox57+ or palemoon?

**Comment by Lootyhoof** [comment]
This is not possible in Basilisk directly but can be enabled by using [Classic Theme Restorer](https://github.com/Aris-t2/ClassicThemeRestorer/releases) (use latest release and above only - currently `1.7.8.2019.02.26`). This supports these features and many more (though not all are supported by Photonic due to how they were implemented in the extension).

Alternatively (and for the features it seems you want, it seems the best option) it would be better to use Pale Moon instead of Basilisk. Both are actively developed and supported, so one will not replace the other.
