### ISSUE TITLE
[feature request] move refresh button to left

### ISSUE THREAD

**Issue by hosxy** [Lootyhoof/photonic#4]
Hello，Do you consider moving refresh button to left？like palemoon / firefox57+
![批注 2019-03-24 220916](https://user-images.githubusercontent.com/17108640/54880643-bd964380-4e81-11e9-8d32-1fcf9b8de177.png)

**Comment by Lootyhoof** [comment]
This is not possible in Basilisk directly but can be enabled by using [Classic Theme Restorer](https://github.com/Aris-t2/ClassicThemeRestorer/releases) (use latest release and above only - currently `1.7.8.2019.02.26`). This supports these features and many more (though not all are supported by Photonic due to how they were implemented in the extension).

Alternatively (and for the features it seems you want, it seems the best option) it would be better to use Pale Moon instead of Basilisk. Both are actively developed and supported, so one will not replace the other.
